<?php

use App\Models\Faq;

$faqs = [
    ['question' => 'What is DigiCoders Technologies Pvt. Ltd.?', 'answer' => 'DigiCoders Technologies Pvt. Ltd. is a professional IT Training and Internship company in Gorakhpur that provides practical training programs for Diploma (CS/IT), B.Tech (Computer Science/IT), BCA, MCA, and other technical students. We focus on live projects, industry-oriented learning, internship certification, and placement assistance.', 'category' => 'general'],
    ['question' => 'Which students can join DigiCoders training programs?', 'answer' => 'Students pursuing Diploma in Computer Science or Information Technology, B.Tech (CS/IT), BCA, MCA, B.Sc IT, and fresh graduates can join our training programs. Beginners as well as students with basic programming knowledge are welcome.', 'category' => 'general'],
    ['question' => 'What types of training programs do you offer?', 'answer' => 'We provide Summer Training, Winter Training, Industrial Training, Apprenticeship Training, Internship Programs, Full Stack Development Training, Web Development Training, Python Training, Java Training, PHP Laravel Training, Data Science, AI, and Digital Marketing courses.', 'category' => 'general'],
    ['question' => 'What is Summer Training?', 'answer' => 'Summer Training is a practical learning program conducted during summer vacations. Students work on live projects, improve technical skills, and gain industry experience that helps them prepare for placements and future careers.', 'category' => 'general'],
    ['question' => 'What is Winter Training?', 'answer' => 'Winter Training is designed for students who want to utilize their winter break to enhance programming, development, and software engineering skills through practical sessions and real-world projects.', 'category' => 'general'],
    ['question' => 'What is Industrial Training?', 'answer' => 'Industrial Training provides students with real software development experience by working on live industry projects under experienced mentors. It helps bridge the gap between academic knowledge and professional requirements.', 'category' => 'general'],
    ['question' => 'What is Apprenticeship Training?', 'answer' => 'Apprenticeship Training is an advanced practical program where students gain hands-on experience by working on real client-based projects while learning industry standards, teamwork, and software development practices.', 'category' => 'general'],
    ['question' => 'Do you provide Internship Certificates?', 'answer' => 'Yes. After successfully completing the training or internship program and fulfilling the project requirements, students receive an Internship/Training Completion Certificate from DigiCoders Technologies Pvt. Ltd.', 'category' => 'general'],
    ['question' => 'Which programming languages and technologies are taught?', 'answer' => 'We provide training in PHP, Laravel, Java, Python, C, C++, HTML, CSS, JavaScript, Bootstrap, React, MySQL, Android Development, Full Stack Development, Data Science, AI, and Digital Marketing.', 'category' => 'general'],
    ['question' => 'Are live projects included in the training?', 'answer' => 'Yes. Students work on live projects such as E-Commerce Websites, College Management Systems, Hospital Management Systems, Attendance Systems, Portfolio Websites, and other real-world applications.', 'category' => 'general'],
    ['question' => 'Is the training suitable for beginners?', 'answer' => 'Yes. Our programs start from basic concepts and gradually move to advanced topics, making them suitable for beginners as well as students who want to improve their existing skills.', 'category' => 'general'],
    ['question' => 'Do you provide placement assistance?', 'answer' => 'Yes. DigiCoders provides placement assistance including resume preparation, technical interview guidance, aptitude preparation, mock interviews, and career counseling to help students start their IT careers.', 'category' => 'general'],
    ['question' => 'Why should students choose DigiCoders Technologies Pvt. Ltd.?', 'answer' => 'Students choose DigiCoders because of practical training, experienced trainers, live projects, updated industry curriculum, internship certification, career guidance, and a supportive learning environment focused on real skill development.', 'category' => 'general'],
    ['question' => 'What is the duration of the training programs?', 'answer' => 'Training duration depends on the selected program. Students can choose short-term and long-term options such as 30 Days, 45 Days, 60 Days, 3 Months, or 6 Months according to their academic requirements and career goals.', 'category' => 'general'],
    ['question' => 'Do you provide project guidance for college students?', 'answer' => 'Yes. We help Diploma, B.Tech, BCA, and MCA students build academic and major projects using modern technologies while explaining the complete development process and documentation.', 'category' => 'general'],
    ['question' => 'Will students receive practical coding experience?', 'answer' => 'Absolutely. Every student writes code, builds projects, debugs applications, works with databases, and develops complete software solutions to gain confidence in real development environments.', 'category' => 'general'],
    ['question' => 'Can final-year students join internship programs?', 'answer' => 'Yes. Final-year Diploma, B.Tech, BCA, and MCA students can join our internship programs to improve technical skills, build professional projects, and prepare for campus placements and job opportunities.', 'category' => 'general'],
    ['question' => 'What career opportunities are available after completing the training?', 'answer' => 'After completing the training, students can apply for roles such as Web Developer, PHP Developer, Laravel Developer, Java Developer, Python Developer, Full Stack Developer, Software Engineer, Android Developer, Data Analyst, and Digital Marketing Executive.', 'category' => 'general'],
    ['question' => 'How can students enroll in DigiCoders training programs?', 'answer' => 'Students can enroll by filling out the online registration form, contacting our admission team, visiting our training center, or connecting through phone, email, or WhatsApp for complete course information and admission guidance.', 'category' => 'general'],
    ['question' => 'Does DigiCoders provide both online and offline training?', 'answer' => 'Yes. DigiCoders Technologies Pvt. Ltd. offers both classroom and online training programs, allowing students from Gorakhpur and other cities to learn from experienced trainers with access to practical sessions, live projects, and mentorship.', 'category' => 'general'],
];

foreach ($faqs as $faq) {
    Faq::create($faq);
}
echo 'Done! Total FAQs: '.Faq::count().PHP_EOL;
